name: ""
description: ""

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true

safe:        false
auto:        true
server:      false
server_port: 4000
baseurl:     /
url:         http://localhost:4000
source:      .
destination: ./_site
plugins:     ./_plugins
future:      true
